version: '3'

tasks:
  restart:
    desc: "Restart the server"
    cmds:
      - docker compose down
      - docker compose up -d
  clean:
    desc: "Clean the database by clearing the tmp/db directory"
    cmds:
      - docker compose down
      - docker volume rm db-data
      - docker compose up -d
