services:
  api:
    build:
      context: ..
      dockerfile: ./.devcontainer/Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ..:/app
      - /app/node_modules
      - /app/dist
    command: tail -f /dev/null
    environment:
      DATABASE_PATH: /app/database.sqlite
      NODE_ENV: development

volumes:
  db-data:
    name: db-data